### ISSUE TITLE
PRONOM backlog?

### ISSUE THREAD

**Issue by marhop** [digital-preservation/pronom-research-week#8]
Hi,

Will the PRONOM backlog be made available, like last year? (See [here](https://github.com/digital-preservation/pronom-research-week-2019/blob/master/PRONOM%20-%20outline%20entries%20only.csv) and [here](https://github.com/digital-preservation/pronom-research-week-2019/blob/master/PRONOMPUIDsWithoutSignatures.csv).)

Thanks,
Martin

**Comment by Dclipsham** [comment]
Yes, there's a few bits like this forthcoming. Sorry for the delay!

**Comment by marhop** [comment]
There it is, closing. Thanks!
